USE UNIVER;

--2

select PULPIT.PULPIT_NAME AS [Название кафедры]
FROM PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY = FACULTY.FACULTY
WHERE FACULTY.FACULTY IN (SELECT FACULTY FROM PROFESSION WHERE PROFESSION_NAME LIKE N'%технологи_%')

--1
select PULPIT.PULPIT_NAME AS [Название кафедры]
FROM PULPIT
WHERE FACULTY IN (SELECT FACULTY FROM PROFESSION WHERE PROFESSION_NAME LIKE N'%технологи_%')

--3
SELECT DISTINCT PULPIT.PULPIT_NAME AS [Название кафедры]
FROM PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION
ON FACULTY.FACULTY = PROFESSION.FACULTY where PROFESSION.PROFESSION_NAME LIKE N'%технологи_%'

--4
SELECT A1.AUDITORIUM AS [Аудитория], 
    A1.AUDITORIUM_TYPE AS [Тип], 
    A1.AUDITORIUM_CAPACITY AS [Вместимость]
FROM AUDITORIUM AS A1
WHERE A1.AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM.AUDITORIUM_CAPACITY FROM AUDITORIUM WHERE AUDITORIUM.AUDITORIUM_TYPE = A1.AUDITORIUM_TYPE ORDER BY AUDITORIUM.AUDITORIUM_CAPACITY DESC)
ORDER BY A1.AUDITORIUM_CAPACITY DESC

--5
SELECT *
FROM FACULTY
WHERE NOT EXISTS (SELECT FACULTY FROM PULPIT WHERE PULPIT.FACULTY = FACULTY.FACULTY)

--6
select top 1
    (select avg(PROGRESS.NOTE) from PROGRESS where PROGRESS.SUBJECT = N'ОАиП')[ОАиП],
    (select avg(PROGRESS.NOTE) from PROGRESS where PROGRESS.SUBJECT = N'БД')[БД],
    (select avg(PROGRESS.NOTE) from PROGRESS where PROGRESS.SUBJECT = N'СУБД')[СУБД]
from PROGRESS

--7
SELECT IDSTUDENT, SUBJECT, NOTE
FROM PROGRESS
WHERE NOTE >= ALL (
    SELECT NOTE FROM PROGRESS WHERE SUBJECT = N'БД'
);

--8
SELECT IDSTUDENT, SUBJECT, NOTE
FROM PROGRESS
WHERE NOTE > ANY (SELECT NOTE FROM PROGRESS WHERE SUBJECT = N'БД');

--10
SELECT 
    IDSTUDENT, 
    NAME AS [ФИО], 
    BDAY AS [Дата рождения]
FROM STUDENT
WHERE DAY(BDAY) = ANY (
    SELECT DAY(BDAY) 
    FROM STUDENT 
    GROUP BY DAY(BDAY) 
    HAVING COUNT(*) > 1
);