--4 A
--1
USE UNIVER;
GO
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRAN;
SELECT AUDITORIUM_NAME, AUDITORIUM_CAPACITY FROM AUDITORIUM WHERE AUDITORIUM = N'301-1';
--2
COMMIT;

--5 A
--1
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRAN;
SELECT AUDITORIUM_NAME, AUDITORIUM_CAPACITY FROM AUDITORIUM WHERE AUDITORIUM = N'301-1';
--2
commit;

--6 A
--1
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN;
SELECT AUDITORIUM_NAME, AUDITORIUM_CAPACITY FROM AUDITORIUM WHERE AUDITORIUM = N'301-1';
--2
Commit;

--7 A
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN;
SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE = N'ЛК';
commit;