--4 B
--1
USE UNIVER;
GO
BEGIN TRAN;
UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 290 WHERE AUDITORIUM = N'301-1';
--2
ROLLBACK;

--5 B
--1
BEGIN TRAN;
UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 200 WHERE AUDITORIUM = N'301-1';
COMMIT;

--6 B
BEGIN TRAN;
UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 500 WHERE AUDITORIUM = N'301-1';
rollback;

--7 B
BEGIN TRAN;
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY) 
VALUES (N'999-9', N'Тестовая', N'ЛК', 100);
rollback;