USE UNIVER;
GO

PRINT N'До начала: @@TRANCOUNT = ' + CAST(@@TRANCOUNT AS VARCHAR);

BEGIN TRAN OuterTran;
    PRINT N'После 1-го BEGIN: @@TRANCOUNT = ' + CAST(@@TRANCOUNT AS VARCHAR);
    
    INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES (N'ТЕСТ1', N'Факультет 1');

    BEGIN TRAN InnerTran;
        PRINT N'После 2-го BEGIN: @@TRANCOUNT = ' + CAST(@@TRANCOUNT AS VARCHAR);
        
        INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES (N'ТЕСТ2', N'Факультет 2');
        
    COMMIT TRAN InnerTran;
    PRINT N'После 1-го COMMIT: @@TRANCOUNT = ' + CAST(@@TRANCOUNT AS VARCHAR);

ROLLBACK TRAN OuterTran; 
PRINT N'После ROLLBACK: @@TRANCOUNT = ' + CAST(@@TRANCOUNT AS VARCHAR);

SELECT * FROM FACULTY WHERE FACULTY LIKE N'ТЕСТ%';
GO