USE UNIVER;
GO

IF OBJECT_ID('AUDITORIUM', 'U') IS NOT NULL 
    DROP TABLE AUDITORIUM;
GO

IF OBJECT_ID('AUDITORIUM_TYPE', 'U') IS NOT NULL 
    DROP TABLE AUDITORIUM_TYPE;
GO

CREATE TABLE AUDITORIUM_TYPE 
( 
    AUDITORIUM_TYPE nvarchar(10) CONSTRAINT PK_AUDITORIUM_TYPE PRIMARY KEY, 
    AUDITORIUM_TYPENAME nvarchar(30) 
);
GO

CREATE TABLE AUDITORIUM 
( 
    AUDITORIUM nvarchar(20) CONSTRAINT PK_AUDITORIUM PRIMARY KEY, 
    AUDITORIUM_NAME nvarchar(50),
    AUDITORIUM_TYPE nvarchar(10) CONSTRAINT FK_AUDITORIUM_TYPE FOREIGN KEY REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE), 
    AUDITORIUM_CAPACITY integer CONSTRAINT CHK_AUDITORIUM_CAPACITY DEFAULT 1 CHECK (AUDITORIUM_CAPACITY BETWEEN 1 AND 300)
);
GO

INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME)
VALUES 
    (N'ЛБ-X', N'Химическая лаборатория'),
    (N'ЛБ-К', N'Компьютерный класс'),
    (N'ЛБ-СК', N'Спец. компьютерный класс'),
    (N'ЛК', N'Лекционная'),
    (N'ЛК-К', N'Лекционная с уст. проектором');
GO

INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY)
VALUES 
    (N'301-1', N'301-1', N'ЛБ-К', 15),
    (N'304-4', N'304-4', N'ЛБ-К', 90),
    (N'313-1', N'313-1', N'ЛК-К', 60),
    (N'314-4', N'314-4', N'ЛК', 90),
    (N'320-4', N'320-4', N'ЛК', 90),
    (N'324-1', N'324-1', N'ЛК-К', 50),
    (N'413-1', N'413-1', N'ЛБ-К', 15),
    (N'423-1', N'423-1', N'ЛБ-К', 90),
    (N'206-1', N'206-1', N'ЛБ-К', 15),
    (N'236-1', N'236-1', N'ЛК', 60),
    (N'408-2', N'408-2', N'ЛК', 90);
GO