USE UNIVER;
GO

SELECT 
    F.FACULTY AS [Факультет], 
    P.PULPIT AS [Кафедра], 
    G.PROFESSION AS [Специальность], 
    SUB.SUBJECT_NAME AS [Дисциплина], 
    S.NAME AS [Имя Студента],
    CASE PR.NOTE
        WHEN 6 THEN N'шесть'
        WHEN 7 THEN N'семь'
        WHEN 8 THEN N'восемь'
    END AS [Оценка]
FROM 
    PROGRESS AS PR
INNER JOIN 
    STUDENT AS S ON PR.IDSTUDENT = S.IDSTUDENT
INNER JOIN 
    GROUPS AS G ON S.IDGROUP = G.IDGROUP
INNER JOIN 
    FACULTY AS F ON G.FACULTY = F.FACULTY
INNER JOIN 
    SUBJECT AS SUB ON PR.SUBJECT = SUB.SUBJECT
INNER JOIN 
    PULPIT AS P ON SUB.PULPIT = P.PULPIT

WHERE 
    PR.NOTE BETWEEN 6 AND 8

ORDER BY 
    PR.NOTE DESC;