USE UNIVER

select * 
from PULPIT P FULL OUTER JOIN TEACHER T
ON P.PULPIT = T.PULPIT
WHERE T.PULPIT IS NULL

select * 
from TEACHER T FULL OUTER JOIN PULPIT P
ON P.PULPIT = T.PULPIT
WHERE T.PULPIT IS NULL

select *
from TEACHER T FULL OUTER JOIN PULPIT P
ON P.PULPIT = T.PULPIT
WHERE T.PULPIT IS NOT NULL