use UNIVER;

Select AUDITORIUM.AUDITORIUM_NAME, TIMETABLE.DAYSOFWEEK
FROM AUDITORIUM LEFT JOIN TIMETABLE
ON AUDITORIUM.AUDITORIUM_NAME = TIMETABLE.AUDITORIUM_NAME
WHERE TIMETABLE.DAYSOFWEEK=N'Понедельник' OR TIMETABLE.DAYSOFWEEK is null