USE UNIVER;

SELECT 
    A.AUDITORIUM_NAME AS [Свободная аудитория]
FROM AUDITORIUM AS A
LEFT JOIN TIMETABLE AS T 
    ON A.AUDITORIUM = T.AUDITORIUM_NAME 
    AND T.DAYSOFWEEK = N'Понедельник' 
    AND T.LESSON = 2
WHERE T.ID_TIMETABLE IS NULL;


SELECT DISTINCT 
    T1.TEACHER AS [Преподаватель], 
    T1.DAYSOFWEEK AS [День недели], 
    (T1.LESSON + 1) AS [Номер пары (окно)]
FROM TIMETABLE AS T1
INNER JOIN TIMETABLE AS T2 
    ON T1.TEACHER = T2.TEACHER 
    AND T1.DAYSOFWEEK = T2.DAYSOFWEEK 
    AND T2.LESSON = T1.LESSON + 2
LEFT JOIN TIMETABLE AS T_Window 
    ON T1.TEACHER = T_Window.TEACHER 
    AND T1.DAYSOFWEEK = T_Window.DAYSOFWEEK 
    AND T_Window.LESSON = T1.LESSON + 1
WHERE T_Window.ID_TIMETABLE IS NULL;

SELECT DISTINCT 
    T1.IDGROUP AS [Группа], 
    T1.DAYSOFWEEK AS [День недели], 
    (T1.LESSON + 1) AS [Номер пары (окно)]
FROM TIMETABLE AS T1
INNER JOIN TIMETABLE AS T2 
    ON T1.IDGROUP = T2.IDGROUP 
    AND T1.DAYSOFWEEK = T2.DAYSOFWEEK 
    AND T2.LESSON = T1.LESSON + 2
LEFT JOIN TIMETABLE AS T_Window 
    ON T1.IDGROUP = T_Window.IDGROUP 
    AND T1.DAYSOFWEEK = T_Window.DAYSOFWEEK 
    AND T_Window.LESSON = T1.LESSON + 1
WHERE T_Window.ID_TIMETABLE IS NULL;