<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ANC25_WEBAPI_DLL\ANC25_WEBAPI_DLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DAL_Celebrity">
      <HintPath>..\..\..\Lab_6\ASPA\DAL_Celebrity\bin\Debug\net8.0\DAL_Celebrity.dll</HintPath>
    </Reference>
    <Reference Include="DAL_Celebrity_MSSQL">
      <HintPath>..\..\..\Lab_6\ASPA\DAL_Celebrity_MSSQL\bin\Debug\net8.0\DAL_Celebrity_MSSQL.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CountryCodes\" />
  </ItemGroup>

</Project>
